graceful:
  timeout: 5s

grpc_server:
  host: 0.0.0.0
  port: 7002
  max_connection_idle: 5m
  max_connection_age: 5m
  timeout: 5s
  time: 120m

http_server:
  port: 8082

kafka:
  brokers: [ "kafka:9092" ]

outbox:
  limits:
    locked_keys_limit: 100
    messages_limit: 1000
    max_err_count_for_message: 5

  topics:
    task-events:
      batch_size: 100
      worker:
        interval: 5s
        concurrency: 1

postgres:
  host: task-postgres
  port: 5432
  user: postgres
  password: "postgres"
  database: tasks
  max_connections: 10
  min_connections: 3
  min_idle_connections: 3
  max_con_lifetime: 5s

categories:
  file_path: "/etc/task-service/categories.json"
